# Configure all environments according to your file at ~/.aws/config
# list of configured profiles
accounts:
  - default

# definition of filters and sort criteria can be found here:
# https://docs.aws.amazon.com/cli/latest/reference/securityhub/get-findings.html

# filters to be used to filter for security findints
filters:
  - filter_name: WorkflowStatus
    value: NEW
    comparison: EQUALS

  - filter_name: RecordState
    value: ACTIVE
    comparison: EQUALS

  - filter_name: ProductName
    value: Config
    comparison: EQUALS

  - filter_name: ComplianceStatus
    value: FAILED
    comparison: EQUALS

  - filter_name: AwsAccountId
    value: "111111111111"
    comparison: EQUALS

# sorting of the return list
sort_criteria:
  field: SeverityLabel
  sort_order: asc